version: '3.9'

services:
  db:
    image: postgres:16
    container_name: carshop_db
    environment:
      POSTGRES_DB: carshop_db
      POSTGRES_USER: carshop_user
      POSTGRES_PASSWORD: carshop123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: carshop_web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=carshop_project.settings
      - DEBUG=1

volumes:
  postgres_data: