# Generated by Django 5.2.7 on 2025-11-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('toyota', 'Toyota'), ('bmw', 'BMW'), ('audi', 'Audi'), ('mercedes', 'Mercedes-Benz'), ('kia', 'Kia'), ('hyundai', 'Hyundai'), ('nissan', 'Nissan'), ('honda', 'Honda'), ('tesla', 'Tesla'), ('ford', 'Ford')], max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег (км)')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Цвет')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Каталог машин',
                'ordering': ['-created_at'],
            },
        ),
    ]
